const FETCH_POST_COMMENTS_START = "FETCH_POST_COMMENTS_START"; 
const FETCH_POST_COMMENTS_SUCCESS = "FETCH_POST_COMMENTS_SUCCESS"; 
const FETCH_POST_COMMENTS_FAILURE = "FETCH_POST_COMMENTS_FAILURE"; 

export {
    FETCH_POST_COMMENTS_START,
    FETCH_POST_COMMENTS_SUCCESS,
    FETCH_POST_COMMENTS_FAILURE,
};
