const FETCH_POST_COMMENTS_START = "FETCH_POST_COMMENTS_START"; 
const FETCH_POST_COMMENTS_SUCCESS = "FETCH_POST_COMMENTS_SUCCESS"; 
const FETCH_POST_COMMENTS_FAILURE = "FETCH_POST_COMMENTS_FAILURE"; 
const SAVE_COMMENT_START = "SAVE_COMMENT_START";
const SAVE_COMMENT_SUCCESS = "SAVE_COMMENT_SUCCESS";
const SAVE_COMMENT_FAILURE = "SAVE_COMMENT_FAILURE";

export {
    FETCH_POST_COMMENTS_START,
    FETCH_POST_COMMENTS_SUCCESS,
    FETCH_POST_COMMENTS_FAILURE,
    SAVE_COMMENT_START,
    SAVE_COMMENT_SUCCESS,
    SAVE_COMMENT_FAILURE
};
